### ISSUE TITLE
Searching based on synonyms

### ISSUE THREAD

**Issue by Rien777** [buildingsmart-community/bSDD-filter-UI#41]
At this moment, added synonyms to a class aren't working when searching in the bSDD Revit plugin. It would be very helpful if this could be implemented in the plugin, as this would make searching a lot more approachable.

I noticed that in the API documentation, the search function /api/Class/Search/v1 does make use of synonyms.

Regards,

René Sondermeijer

(https://github.com/buildingsmart-community/bSDD-Revit-plugin/issues/98)

**Comment by janbrouwer** [comment]
Yes, it should

**Comment by Rien777** [comment]
The bSDD search pages does search synonyms:
![image](https://github.com/user-attachments/assets/331450cd-c7e3-47b7-953c-49d0ea93cd2b)
![image](https://github.com/user-attachments/assets/a8d90795-39b4-44ca-a9f3-e294799afe61)

**Comment by jbrouwerdigibase** [comment]
Fixed in https://github.com/buildingsmart-community/bSDD-filter-UI/commit/62571f59e0c76010a9cac05b3e3ee84a8e5369f1
